This idea is to calculate the probability of different states with a Markov Chain analysis. 

This will focus on the world's greatest game: Snakes and Ladders.


In [1]:
dieMax = 6; # largest you can roll. The smallest you can roll is 1

possibleStateNumber = 16; # This should be a square of some number, like 16,25,36, etc... because the board is square
transitionMatrix = zeros(possibleStateNumber, possibleStateNumber);
transitionMatrix

transitionMatrix =

   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0 

In [2]:
# Because players can roll higher than the available spaces then we need to catch those extras and increase the value of the final score
# Otherwise, all possibilities should have a score equal to 1/6, or however many sides the die has

for i =1:possibleStateNumber
    overshootCount = 0;
    for j =1+i:dieMax+i
        if j > possibleStateNumber
            overshootCount = overshootCount + 1;
        else
            transitionMatrix(i,j) = 1/dieMax;
        end
    end
    if overshootCount > 0
        transitionMatrix(i,possibleStateNumber) = transitionMatrix(i,possibleStateNumber) + overshootCount/dieMax;
    end
end

transitionMatrix

transitionMatrix =

 Columns 1 through 8:

   0.00000   0.16667   0.16667   0.16667   0.16667   0.16667   0.16667   0.00000
   0.00000   0.00000   0.16667   0.16667   0.16667   0.16667   0.16667   0.16667
   0.00000   0.00000   0.00000   0.16667   0.16667   0.16667   0.16667   0.16667
   0.00000   0.00000   0.00000   0.00000   0.16667   0.16667   0.16667   0.16667
   0.00000   0.00000   0.00000   0.00000   0.00000   0.16667   0.16667   0.16667
   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.16667   0.16667
   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.16667
   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000
   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000
   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000
   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000
   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.0

Let's introduce some snakes and ladders

These have the same structure, in that they take the player from position 1 and take them to position 2, in the form (1,2)

Snakes and ladders can end at the same place, but can't start at the same place. A ladder can't end where a snake starts, and vice-versa.

For every state (row) in the transition matrix, replace the probability of the first index with zero, and add the probability to the second index

In [3]:
snakes = [
    13 11;
    10 6;
    15 2
]

snakes =

   13   11
   10    6
   15    2



In [4]:
ladders = [
    3 6;
    7 11;
    5 12
]

ladders =

    3    6
    7   11
    5   12



In [5]:
# Are snakes and ladders equal?

snakePenalty = 0;
for s =1:length(snakes)
    snakePenalty = snakePenalty + snakes(s,1) - snakes(s,2);
end
snakePenalty

ladderReward = 0;
for l =1:length(ladders)
    ladderReward = ladderReward + ladders(l,2) - ladders(l,1);
end
ladderReward

snakePenalty =  19
ladderReward =  14


In [6]:
# Move probabilities from snake head to tail, ladder bottom to top

for i =1:length(transitionMatrix)
    for s =1:length(snakes)
        head = snakes(s, 1);
        tail = snakes(s, 2);
        probability = transitionMatrix(i, head);
        transitionMatrix(i, head) = 0;
        transitionMatrix(i, tail) = transitionMatrix(i, tail) + probability;
    end
    
    for l =1:length(ladders)
        bottom = snakes(l, 1);
        top = snakes(l, 2);
        probability = transitionMatrix(i, bottom);
        transitionMatrix(i, bottom) = 0;
        transitionMatrix(i, top) = transitionMatrix(i, top) + probability;
    end
end

In [7]:
transitionMatrix

transitionMatrix =

 Columns 1 through 8:

   0.00000   0.16667   0.16667   0.16667   0.16667   0.16667   0.16667   0.00000
   0.00000   0.00000   0.16667   0.16667   0.16667   0.16667   0.16667   0.16667
   0.00000   0.00000   0.00000   0.16667   0.16667   0.16667   0.16667   0.16667
   0.00000   0.00000   0.00000   0.00000   0.16667   0.33333   0.16667   0.16667
   0.00000   0.00000   0.00000   0.00000   0.00000   0.33333   0.16667   0.16667
   0.00000   0.00000   0.00000   0.00000   0.00000   0.16667   0.16667   0.16667
   0.00000   0.00000   0.00000   0.00000   0.00000   0.16667   0.00000   0.16667
   0.00000   0.00000   0.00000   0.00000   0.00000   0.16667   0.00000   0.00000
   0.00000   0.16667   0.00000   0.00000   0.00000   0.16667   0.00000   0.00000
   0.00000   0.16667   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000
   0.00000   0.16667   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000
   0.00000   0.16667   0.00000   0.00000   0.00000   0.00000   0.0

In [8]:
initialState = zeros(1,possibleStateNumber);
initialState(1,1) = 1

initialState =

   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0



In [9]:
# Starting at the square=1, how what's the probability of being at any given square after n turns?

n = 5
initialState*transitionMatrix^n

n =  5
ans =

 Columns 1 through 8:

   0.00000   0.07279   0.01530   0.01672   0.01813   0.06096   0.03408   0.04051

 Columns 9 through 16:

   0.03344   0.00000   0.11175   0.06803   0.00000   0.06546   0.00000   0.46283



### FURTHER IDEA:

Is it possible to apply linear programming to this model to optimise it somehow? The more obvious option is to apply a Monte Carlo simulation.

objective function:
- minimise the number of turns to reach the absorbing state with 0.5 probability

Constraints:
- limited number of ladders
- ladders of limited size
- every row in the matrix must add up to 1 to preserve its nature as a transition matrix
- every row in the matrix has 6 non-zero numbers
- every non-zero number is a multiple of 1/6

It seems a bit hard. It might be better to do as a Monte Carlo simulation.

There are some obvious questions to pose:
- Can you minimise the number of turns to reach the absorbing state by rearranging the snakes and ladders, while keeping the balance between penalty and reward?
- Does increasing or decreasing the number of both do anything? In other words, do the penalty and rewards have any material impact on the game other than to make it interesting for children?